account_id = "e3800962ed5e416e565f49c823868cf3"
name = "email-to-r2-worker"
main = "index.ts"
compatibility_date = "2024-03-11"

[vars]
FORWARD_EMAIL = "kazuki175209@gmail.com"

[[r2_buckets]]
binding = "MY_BUCKET" # コード内で使う変数名
bucket_name = "ruxelmail" # 実際に作ったバケット名
